log_dir: "./logs"
debug: true

common_log:
  filename: "common.log"
  max_size: 20
  max_backups: 5
  max_age: 30
  compress: true

error_log:
  filename: "errors.log"
  max_size: 10
  max_backups: 10
  max_age: 60
  compress: true

output_log:
  filename: "output.log"
  max_size: 15
  max_backups: 3
  max_age: 7
  compress: false

console:
  enabled: true
  level: "debug"